stages:
    - build
    - package
    - test


variables:
    ENV: "dev"

.printinfo: &printinfo
    - echo "Bonjour depuis ${ENV}, il est $(date)"
    - echo "Nous sommes dans l'étape '${CI_JOB_STAGE}' et dans le job '${CI_JOB_NAME}'"

before_script:
  - echo "Avant tous les autres jobs"
  - *printinfo
  
after_script:
  - echo "Après tous les autres jobs"
  - echo "Il est $(date)"

build:java:
  stage: build
  tags: [docker]
  before_script:
    - echo "Nous sommes à l'étape '${CI_JOB_STAGE}' et avant le '${CI_JOB_NAME}'"
  script:
    - *printinfo
    - echo "Répertoire courant $(pwd)"
    - ls -la
    - echo "Racine:"
    - ls -la /
    - echo "Variables d'environnements:"
    - printenv
    - echo "Run build java"
    
build:js:
  stage: build
  tags: [docker]
  script:
    - *printinfo
    - echo "Run build js"

package:gz:
  stage: package
  tags: [docker]
  script:
    - *printinfo
    - echo "mon simple fichier texte" | gzip > simplepackage.gz
  artifacts:
    paths:
      - simplepackage.gz
    expire_in: 1 hour

test:artifact:
  stage: test
  tags: [docker]
  script: #!/bin/bash
    - *printinfo
    - ls -la
    - [[ -f simplepackage.gz ]] && gzip -t simplepackage.gz && gzip -l simplepackage.gz && echo "Artifact is generated"
  dependencies:
    - package:gz
