stages:
    - build


variables:
    ENV: "dev"
build backend:
  stage: build
  tags: [docker]
  script:
    - echo "Bonjour ${ENV}"
    - echo "Répertoire courant $(pwd)"
    - ls -la
    - echo "Racine:"
    - ls -la /
    - echo "Variables d'environnements:"
    - printenv
    
